### ISSUE TITLE
Please explain node setup

### ISSUE THREAD

**Issue by gitsamhub** [atticus-lv/color_helper#1]
Hi, Thank you for creating such a wonderful addon!

However, I am unable to figure out how are you able to dynamically change colors just by refreshing palette. Could you please post your node setup, or instruction on how to set it up.

**Comment by atticus-lv** [comment]
Just hover mouse over the refresh button. 
You will find it turns red when you hold CTRL to press it, which mean now what you do to this palatte will be automatically update.
> CTRL click to turn it off.Or bind any node group that exist with this palette(This node group will be override)

![image](https://user-images.githubusercontent.com/64118610/187497354-e8cc2746-7919-4c37-b537-bf68409ea3b3.png)

**Comment by gitsamhub** [comment]
![image](https://user-images.githubusercontent.com/79096837/187511511-45b81caf-aa7f-428d-ad1d-57c9a25e7460.png)
When I pressed SHIFT+CLICK , it gives me above error.
After discovering Palette node, i manually added that to my material color. And gave random to ramp factor as shown in screenshot. Is there there anything I am missing? It seems that you had some other node setup in gif image on readme file.

It would be of great help If there is any small node setup tutorial(even gif image will do).

**Comment by gitsamhub** [comment]
Thank you.
