### ISSUE TITLE
addon can't be enables

### ISSUE THREAD

**Issue by sojuzpl** [atticus-lv/color_helper#6]
macOS + Blender 3.6.5

After installing 0.4.2 and when I tried to enable the addon I got this message:

![Zrzut ekranu 2023-11-26 o 00 19 33](https://github.com/atticus-lv/color_helper/assets/9154590/e5bf7a1f-2fb6-4ff0-89f3-9d4ab516de30)

**Comment by atticus-lv** [comment]
remove the version like -0.4 of the folder name

**Comment by sojuzpl** [comment]
THX!
